# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set timestamp as version
        id: version
        run: echo "VERSION=$(date +%s)" >> $GITHUB_ENV

      - name: Replace version placeholder in HTML files
        run: |
          find . -name "*.html" -exec sed -i "s/<!-- VERSION -->/${{ env.VERSION }}/g" {} \;
      
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # - name: FTP Upload
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      #   with:
      #     server: ${{ secrets.FTP_HOST }}
      #     username: ${{ secrets.FTP_USERNAME }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     protocol: ftp
      #     port: 21
      #     local-dir: ./
      #     server-dir: /ootrjsonsearch.org/htdocs/
      #     exclude: |
      #       **/.git*
      #       **/.git*/**
      #       **/node_modules/**