name: Simple FTP Upload

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: FTP Upload to ftpupload.net
        uses: pontago/lftp-deploy-action@v1.0.1
        with:
          host: ${{ secrets.FTP_HOST }}                # set to ftpupload.net
          username: ${{ secrets.FTP_USERNAME }}        # your username
          password: ${{ secrets.FTP_PASSWORD }}        # your password
          port: "21"
          protocol: "ftp"
          local_dir: "."                               # root of the repo
          remote_dir: "/ootrjsonsearch.org/htdocs"
          create_remote_dir: true
          verify_cert: true
          dry_run: false
          debug: false
          timeout: 30
          max_retries: 3
