name: Simple FTP Upload

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: FTP Upload to ftpupload.net
        uses: pontago/lftp-deploy-action@v1.0.1
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: "21"
          protocol: "ftp"
          local_dir: "."
          remote_dir: "/ootrjsonsearch.org/htdocs"
          create_remote_dir: true
          verify_cert: true
          dry_run: false
          debug: false
          timeout: 30
          max_retries: 3
          script: |
            # Change to the target remote directory
            cd /ootrjsonsearch.org/htdocs
            # Exclude all hidden folders and specific files (e.g., .git)
            set mirror:exclude-regex "^\..*|^(\.git|\.github|\.gitignore|README\.md)$"
            # Upload files to the correct remote directory
            mirror --reverse --only-newer --delete --verbose .
